### PR TITLE
Auto rename duplicate headers

### LINKED ISSUE #90: Handle duplicated headers
Hey @doyaaaaaken thank you very much for this library!

https://github.com/doyaaaaaken/kotlin-csv/blob/48510de1ce9856c672b5871c7363cf56f13633cf/src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt#L63-L64

When reading all lines with headers, a duplicate check is performed and `MalformedCSVException` thrown.
Since columns in a row are accessed by their index headers could simply be deduplicated by appending something like an occurrence indicator to the header name.

## Example:
| just | some | example | example | headers |
|------|------|---------|---------|---------|
| A    | B    | C       | D       | E       |

The header `example` appears twice. According to the suggestion the second occurrence could be named `example_01`.
Main benefit would be to not have a runtime exception thrown and not needing to rename columns in the original file to have it processed.

I know this would introduce some "magic" and I hope that wouldn't collide with your goal of having a simple library.
The required functionality would be just a few lines of code and I'd very gladly do a PR myself, just first wanted to get your thoughts on this.

### PR DESCRIPTION
**Pull request by JulianSudendorf**
Resolves #90

### CODE REVIEW

File: src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt [hunk 1]
```diff
@@ -107,4 +111,25 @@ class CsvFileReader internal constructor(
...
+        val occurrences = headers.toSet().associateWith { 1 }.toMutableMap()
+        return headers.map { header ->
+            occurrences[header]?.let { occurred ->
+                when {
+                    occurred > 1 -> "${header}_$occurred"
+                    else -> header
+                }.also {
+                    occurrences[header] = occurred + 1
+                }
+            } ?: throw RuntimeException("a")
```
Comment (JulianSudendorf) [inline src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt:132]: Be aware that this is case insensitive. So you still can have (`Example`,`exAmple`, `example`). As of now this purposely doesn't catch ambiguous duplicates.

File: src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/dsl/context/CsvReaderContext.kt [hunk 2]
```diff
@@ -59,6 +59,15 @@ interface ICsvReaderContext {
      * If a invalid row which has different number of fields from other rows is found, skip it or not (=throw an exception).
      */
     val skipMissMatchedRow: Boolean
+
+    /**
+     * If a header occurs multiple times whether auto renaming should be applied when `readAllWithHeaderAsSequence()` (=throw an exception).
+     *
+     * Renaming is done based on occurrence and only applied from the first detected duplicate onwards.
```
Comment (doyaaaaaken) [inline src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/dsl/context/CsvReaderContext.kt:66]: 👍

File: src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt [hunk 3]
```diff
@@ -59,9 +59,13 @@ class CsvFileReader internal constructor(
...
     fun readAllWithHeaderAsSequence(): Sequence<Map<String, String>> {
-        val headers = readNext() ?: return emptySequence()
-        val duplicated = findDuplicate(headers)
-        if (duplicated != null) throw MalformedCSVException("header '$duplicated' is duplicated")
+        var headers = readNext() ?: return emptySequence()
+        if (ctx.autoRenameDuplicateHeaders) {
+            headers = deduplicateHeaders(headers)
+        } else {
+            val duplicated = findDuplicate(headers)
+            if (duplicated != null) throw MalformedCSVException("header '$duplicated' is duplicated")
```
Comment (doyaaaaaken) [inline src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt:67]: It would be nice to include a hint in the MalformedCSVException message, which indicates the `autoRenameDuplicateHeaders` option can avoid Exception.

File: src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt [hunk 4]
```diff
@@ -107,4 +111,24 @@ class CsvFileReader internal constructor(
...
     }
+
+    /**
+     * deduplicate headers based on occurrence by appending "_<NUM>"
+     * Ex: [a,b,b,c,a] => [a,b,b_2,c,a_2]
+     *
+     * @return return headers as List<String>.
+     *
+     */
+    private fun deduplicateHeaders(headers: List<String>): List<String> {
```
Comment (doyaaaaaken) [inline src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt:122]: It seems that this logic cannot handle a CSV file's header `[a, a, a_1]`.
In this case, I think the auto-renamed header should be `[a, a_2, a_1]` (or `[a, a_1_1, a_1]`).

File: src/jvmTest/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvReaderTest.kt [hunk 5]
```diff
@@ -206,6 +206,23 @@ class CsvReaderTest : WordSpec({
...
+                mapOf("some" to "a", "example" to "b", "example_2" to "b", "headers" to "c"),
+                mapOf("some" to "d", "example" to "e", "example_2" to "e", "headers" to "f")
+            )
+            val file = readTestDataFile("with-duplicate-header.csv")
+            val result = csvReader {
+                autoRenameDuplicateHeaders = true
+            }.readAllWithHeader(file)
+            result shouldBe deduplicateExpected
+        }
+
```
Comment (doyaaaaaken) [inline src/jvmTest/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvReaderTest.kt:225]: 👍

**Review by doyaaaaaken — COMMENTED** [review]
Thanks for your PR! 🙏

File: src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt (hunk 4 above)
Comment (JulianSudendorf) [reply src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt:122]: That's a tricky case! Thanks for bringing this up, I'll put some thought into it.

File: src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt (hunk 1 above)
Comment (doyaaaaaken) [reply src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt]: You said `case insensitive`, but is that misuse of `case sensitive`?

Comment (JulianSudendorf) [reply src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt]: Yes, fixed it in the original comment.

File: src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt (hunk 4 above)
Comment (doyaaaaaken) [reply src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt:122]: @JulianSudendorf 
Hi, if you don't mind, I could merge this PR and do this fix on my end.

Comment (JulianSudendorf) [reply src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt:122]: Hey @doyaaaaaken I'm very sorry for the delay. I experimented with a few options, but didn't like any of them completely. The most favorable option would be to introduce a new exception that indicates the naming collision, because automatically renaming the collision again can be very dependent o the use case. If you're comfortable merging the PR in the current state and handle the rest on your side I wouldn't mind at all :)

Comment (doyaaaaaken) [reply src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt:122]: > The most favorable option would be to introduce a new exception that indicates the naming collision, because automatically renaming the collision again can be very dependent o the use case.

Sounds good, I'll consider it. Thanks.

Comment (doyaaaaaken) [reply src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt:122]: I implemented like this. Thanks.
https://github.com/doyaaaaaken/kotlin-csv/pull/92/files#diff-63c02e69ac51828469fa44563f04f35ea00bc908a5af8343828a683a42bf11baR131-R132
